# Manual clustering with phy

In [1]:
from phy.cluster.manual.session import Session

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%gui qt

In [3]:
filename = "/data/spikesorting/4_20141130/20141130_all.kwik"

In [4]:
session = Session()

In [5]:
session.open(filename)

In [6]:
model = session.model

In [7]:
clustering = session.clustering

In [8]:
model.filename

'/data/spikesorting/4_20141130/20141130_all.kwik'

In [9]:
cs = session.cluster_store

The `session.best_clusters()` accepts any `cluster => quality` function. It returns the list of best clusters by decreasing of quality, according to that function.

In [10]:
session.best_clusters(cs.n_unmasked_channels, 10)

[1, 654, 598, 139, 556, 499, 136, 273, 572, 52]

In [11]:
session.select([654, 598, 139])

In [12]:
session.show_waveforms()

Let's make some manual clustering.

In [13]:
clusters = [654, 598]

In [14]:
session.merge(clusters)

In [15]:
clustering.spikes_in_clusters(clusters)

array([], dtype=int64)

In [16]:
session.undo()

In [17]:
clustering.spikes_in_clusters(clusters)

array([    976,    1518,    5620, ..., 3384941, 3385918, 3387447])

In [18]:
session.redo()

In [19]:
clustering.spikes_in_clusters(clusters)

array([], dtype=int64)

Let's move clusters:

In [20]:
session.cluster_metadata.group(720)

3

In [21]:
session.move([720], 2)

In [22]:
session.cluster_metadata.group(720)

2

In [23]:
session.undo()

In [24]:
session.cluster_metadata.group(720)

3

In [25]:
session.redo()

In [26]:
session.cluster_metadata.group(720)

2

Let's do some splits.

In [27]:
spikes = clustering.spikes_in_clusters([556, 499])
spikes

array([    942,    3164,    3938, ..., 3366635, 3372149, 3384945])

In [28]:
session.split(spikes[::2])

In [29]:
clustering.spikes_in_clusters([556, 499])

array([], dtype=int64)

In [30]:
session.undo()

In [31]:
clustering.spikes_in_clusters([556, 499])

array([    942,    3164,    3938, ..., 3366635, 3372149, 3384945])

In [32]:
session.redo()

In [33]:
clustering.spikes_in_clusters([556, 499])

array([], dtype=int64)

In [34]:
session.save()

2015-04-13 17:10:55  session:449             Saved /data/spikesorting/4_20141130/20141130_all.kwik.
