# Multiple clusterings

In [1]:
import phy
from phy.cluster.manual.session import Session

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%gui qt

In [3]:
filename = "/home/cyrille/1_simple120sec/test_hybrid_120sec.kwik"

There's always a `.kwik.bak` backup file that is created when loading the file (unless the backup already exists). We can use that to recover the original file at the beginning so that we can mess around with the Kwik file without worrying about breaking it.

In [4]:
import os.path as op
import shutil
bak = filename + '.bak'
if op.exists(bak):
    shutil.copyfile(bak, filename)

In [5]:
session = Session()

In [6]:
session.open(filename)

In [7]:
session.model.n_clusters

24

In [8]:
session.show_waveforms()

In [9]:
session.cluster_ids

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25], dtype=uint32)

In [10]:
session.wizard.best_clusters()

[5, 8, 13, 20, 22, 24, 19, 17, 21, 2]

In [11]:
session.select(5)

The list of clusterings in the file:

In [12]:
session.model.clusterings

['main', 'original']

Choose another clustering than the main one:

In [13]:
session.change_clustering('original')

Check the current clustering:

In [14]:
session.model.clustering

'original'

List of clusters in the current clustering:

In [15]:
session.cluster_ids

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25], dtype=uint32)

In [16]:
session.select([6,7])

Move a cluster to a group:

In [17]:
session.cluster_metadata.group(6)

3

In [18]:
session.move([6], 2)

In [19]:
session.cluster_metadata.group(6)

2

Merge two clusters:

In [22]:
session.merge([8,7])

Check the cluster ids.

In [23]:
session.cluster_ids

array([ 2,  3,  4,  5,  6,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26])

Save the changes to the file, in the `original` clustering:

In [24]:
session.save()

2015-04-15 12:22:08  session:462             Saved /home/cyrille/1_simple120sec/test_hybrid_120sec.kwik.
